<a href="https://colab.research.google.com/github/irfan-ardiansyah/data-science-2026/blob/main/Pertemuan%203_Muhammad%20Irfan%20Ardiansyah_250401020175.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [230]:
import pandas as pd, numpy as np
from scipy.stats.mstats import winsorize
from google.colab import drive

# STEP 0 — Load & eksplorasi awal
df = pd.read_csv('housing_dirty.csv')
print('Shape awal:', df.shape)

original_df = df

Shape awal: (130, 7)

In [231]:
print("Data Frame Information")
print(df.info())
print("\nDescribe")
print(df.describe())
print("\nMissing values")
print(df.isnull().sum())

Data Frame Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            130 non-null    int64
 1   luas_m2       112 non-null    float64
 2   harga_juta    113 non-null    float64
 3   kota          130 non-null    object
 4   kamar         120 non-null    float64
 5   tahun_bangun  130 non-null    int64
 6   kondisi       130 non-null    object
dtypes: float64(3), int64(2), object(2)
memory usage: 7.2+ KB
None

Describe
               id      luas_m2    harga_juta       kamar  tahun_bangun
count  130.000000   112.000000  1.130000e+02  120.000000    130.000000
mean    65.500000   267.627679  8.856325e+05    3.433333   2062.638462
std     37.671829   885.664181  9.407144e+06    1.776283    701.684043
min      1.000000   -50.000000 -5.000000e+02    1.000000   1890.000000
25%     33.250000    87.050000  3.450000e+02    2.000000   1991.250000
50%     65.500000   193.800000  6.550000e+02    4.000000   2002.000000
75%     97.750000   280.675000  9.550000e+02    5.000000   2011.750000
max    130.000000  9500.000000  1.000000e+08    6.000000   9999.000000

Missing values
id               0
luas_m2         18
harga_juta      17
kota             0
kamar           10
tahun_bangun     0
kondisi          0
dtype: int64

In [232]:
# STEP 1 — Hapus Duplikat
df.drop_duplicates(inplace=True)
print('Setelah hapus duplikat:', df.shape)

Setelah hapus duplikat: (130, 7)

In [233]:
# STEP 2 — Normalisasi String
df['kota'] = df['kota'].str.strip().str.title()
df['kondisi'] = df['kondisi'].str.strip().str.lower()
print(df.iloc[8])

id                       9
luas_m2               81.2
harga_juta           307.0
kota            Yogyakarta
kamar                  1.0
tahun_bangun          1996
kondisi             sedang
Name: 8, dtype: object

In [234]:
# STEP 3 — Imputasi Missing Values
df['luas_m2'] = df['luas_m2'].fillna(df['luas_m2'].median())
df['harga_juta'] = df['harga_juta'].fillna(df['harga_juta'].median())
df['kamar'] = df['kamar'].fillna(df['kamar'].mode()[0])

df

      id  luas_m2  harga_juta        kota  kamar  tahun_bangun kondisi
0      1    297.0      1084.0       Jogja    2.0          2000    baik
1      2    254.0       761.0       Medan    1.0          1995   bagus
2      3    249.7       895.0       Depok    1.0          1983    baik
3      4     49.7       178.0         Ygy    5.0          2013    baik
4      5    133.4       424.0       Medan    5.0          2004  sedang
..   ...      ...         ...         ...    ...           ...     ...
125  126    330.2      1050.0    Semarang    6.0          1993    baik
126  127    193.8       655.0    Makassar    5.0          2008    baik
127  128     84.1       202.0    Makassar    2.0          1986    baik
128  129     88.0       252.0    Makassar    1.0          1986   bagus
129  130    215.4       941.0  Yogyakarta    1.0          2013   cukup

[130 rows x 7 columns]

In [235]:
# STEP 4 — Tangani Outlier (IQR Fence)
for col in ['harga_juta', 'luas_m2', 'tahun_bangun']:
  Q1, Q3 = df[col].quantile([0.25, 0.75])
  IQR = Q3 - Q1
  df[col] = df[col].clip(Q1-1.5*IQR, Q3+1.5*IQR)

df

      id  luas_m2  harga_juta        kota  kamar  tahun_bangun kondisi
0      1    297.0      1084.0       Jogja    2.0        2000.0    baik
1      2    254.0       761.0       Medan    1.0        1995.0   bagus
2      3    249.7       895.0       Depok    1.0        1983.0    baik
3      4     49.7       178.0         Ygy    5.0        2013.0    baik
4      5    133.4       424.0       Medan    5.0        2004.0  sedang
..   ...      ...         ...         ...    ...           ...     ...
125  126    330.2      1050.0    Semarang    6.0        1993.0    baik
126  127    193.8       655.0    Makassar    5.0        2008.0    baik
127  128     84.1       202.0    Makassar    2.0        1986.0    baik
128  129     88.0       252.0    Makassar    1.0        1986.0   bagus
129  130    215.4       941.0  Yogyakarta    1.0        2013.0   cukup

[130 rows x 7 columns]

In [236]:
# STEP 5 — Validasi & Ekspor
# print(df.isnull())
assert df.isnull().sum().sum() == 0, 'Masih ada missing!'
assert df.duplicated().sum() == 0, 'Masih ada duplikat!'

print('Shape akhir:', df.shape)
df.to_csv('housing_clean.csv', index=False)
print('Dataset bersih tersimpan!')

Shape akhir: (130, 7)
Dataset bersih tersimpan!

In [237]:
# Read json file from URL
import requests
from pandas import json_normalize

json_url = "https://jsonplaceholder.typicode.com/users"
response = requests.get(json_url, timeout=10)

response

In [238]:
# Response status check
if response.status_code == 200:
  data = response.json()
  df = json_normalize(data, sep='_')
  print(df[['id','name','email','address_city']])
else:
  print(f'Error: {response.status_code}')

   id                      name                      email    address_city
0   1             Leanne Graham          Sincere@april.biz     Gwenborough
1   2              Ervin Howell          Shanna@melissa.tv     Wisokyburgh
2   3          Clementine Bauch         Nathan@yesenia.net   McKenziehaven
3   4          Patricia Lebsack  Julianne.OConner@kory.org     South Elvis
4   5          Chelsey Dietrich   Lucio_Hettinger@annie.ca      Roscoeview
5   6      Mrs. Dennis Schulist    Karley_Dach@jasper.info   South Christy
6   7           Kurtis Weissnat     Telly.Hoeger@billy.biz       Howemouth
7   8  Nicholas Runolfsdottir V       Sherwood@rosamond.me       Aliyaview
8   9           Glenna Reichert    Chaim_McDermott@dana.io  Bartholomebury
9  10        Clementina DuBuque     Rey.Padberg@karina.biz     Lebsackbury

In [239]:
params = {'userId': 1} # filter by user
posts = requests.get("https://jsonplaceholder.typicode.com/posts", params=params).json()
df_posts = pd.DataFrame(posts)

df_posts

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
5,1,6,dolorem eum magni eos aperiam quia,ut aspernatur corporis harum nihil quis provid...
6,1,7,magnam facilis autem,dolore placeat quibusdam ea quo vitae\nmagni q...
7,1,8,dolorem dolore est ipsam,dignissimos aperiam dolorem qui eum\nfacilis q...
8,1,9,nesciunt iure omnis dolorem tempora et accusan...,consectetur animi nesciunt iure dolore\nenim q...
9,1,10,optio molestias id quia eum,quo et expedita modi cum officia vel magni\ndo...